attention_resolutions: 32,16,8
base_samples: ''
batch_size: 1
clip_denoised: True
data_dir: ''
dropout: 0.0

#data_root: '/home/cbtil/ST_proj/data/Breast_cancer/'
data_root: '/date/NMI/data/brain glioblastomamultiforme'
all_gene: 40
dataset_use: 'Xenium' # Xenium Visium NBME
SR_times: 10
gene_num: 10
diffusion_steps: 1000
sampling_method: guided # guided

num_channels: 64
num_res_blocks: 1
# model_path: /home/hanyu/JYX/logs_new/x10_Xenium_g10_outRelu_100_t2_0109-1050/model012000.pt

learn_sigma: true
noise_schedule: linear
num_head_channels: 28
num_heads: 4
num_heads_upsample: -1
#num_samples: 50000
predict_xstart: false
resblock_updown: true
rescale_learned_sigmas: false
rescale_timesteps: false
timestep_respacing: '400'
use_checkpoint: false

use_fp16: false
use_kl: false
use_scale_shift_norm: true
