attention_resolutions: 32,16,8
batch_size: 10
data_dir: ''
diffusion_steps: 1000  #change(50-2000)
dropout: 0.0
ema_rate: '0.9999'
fp16_scale_growth: 0.001
data_root: '/date/NMI/data/VisiumHD_moueembryo_sorted_data'
model_path: logs/x5_Xenium_g25_1112-0718/model055000.pt
dataset_use: 'Xenium5k' # Visium NBME
SR_times: 10
gene_num: 10
save_interval: 1000
all_gene: 60

num_channels: 64
num_res_blocks: 1

learn_sigma: true
log_interval: 100
lr: 0.0001
lr_anneal_steps: 0
microbatch: -1
noise_schedule: linear
num_head_channels: 24
num_heads: 4
num_heads_upsample: -1
resblock_updown: true
use_scale_shift_norm: true
rescale_learned_sigmas: false
rescale_timesteps: false
resume_checkpoint: ''
schedule_sampler: uniform
timestep_respacing: ''
use_checkpoint: false
use_fp16: false
use_kl: false
predict_xstart: false
weight_decay: 0.00001
